export enum ErrorCode {
  
  // User
  USER_NOT_FOUND = 1001,
  PIN_MISMATCH = 1002,
  INVALID_PIN = 1003,
  USER_ALREADY_EXISTS = 1004,
  FIRST_USER_MUST_BE_SUPERADMIN = 1005,

  // Access Control
  UNAUTHORIZED = 2001,
  FORBIDDEN = 2002,

  // Order Summary
  ORDER_SUMMARY_NOT_FOUND = 3001,
  ORDER_SUMMARY_PRINT_FAILED = 3002,
  ORDER_SUMMARY_PRINT_HTML_NOT_FOUND = 3003,
  FINISHED_PRODUCT_ADD_FAILED = 3004,
  FINISHED_PRODUCT_NOT_FOUND = 3005,

  // Invalid Data
  UNPROCESSABLE_UNTITY = 8001,

  // Internal Exception
  INTERNAL_EXCEPTION = 9001,
}

export default ErrorCode;
