export * as authService from "@/services/auth.service";
export * as ordersAdminService from "@/services/orders/admin.service";
export * as ordersCustomerService from "@/services/orders/customer.service";
export * as paymentProofService from "@/services/payment-proof.service";
export * as productService from "@/services/product.service";
export * as userService from "@/services/user.service";
export * as cartItemService from "@/services/cart-item.service";
export * as transactionService from "@/services/transaction.service";
export * as reviewService from "@/services/review.service";